micronaut:
  application:
    name: naturecodeStock
  server:
    port: 9090
  endpoints:
    health:
      enabled: true
      sensitive: false
      details-visible: ANONYMOUS
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapiddoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    authentication: bearer 
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ChangeMeWheneverYouAreReadyToChangeMe
netty:
  default:
    allocator:
      max-order: 3

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: true
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/naturecode-stock`}
      user: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD}
      schemas: mn
      default-schema: mn

# datasources:
#   default:
#     url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/naturecode-stock`}
#     username: ${PG_USERNAME:postgres}
#     password: ${PG_PASSWORD}
#     driver-class-name: org.postgresql.Driver
#     schema-generate: NONE
#     dialect: POSTGRES

datasources:
  default:
    url: jdbc:mysql://localhost:3306/naturecode-fundind
    username: root
    password: ${PG_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    schema-generate: NONE
    dialect: MYSQL

liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase/changelog.xml'
      drop-first: false

# jpa:
#   default:
#     packages-to-scan:
#       - "com.naturecode.persistence"
#     properties:
#       hibernate:
#         show_sql: false  
